abstract: login/logout interface to Hatena
author: =head2 new ( [I<\%args>] )
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WWW-HatenaLogin
no_index: 
  directory: 
    - inc
    - t
requires: 
  URI: 0
  WWW::Mechanize: 0
version: 0.02
